### ISSUE TITLE
Question: What is scribe?

### ISSUE THREAD

**Issue by daviddahl** [cottojon/scribe#20]
I found scribe via the dependency graph from the DeepSpeech project. I have been reading the code and wondering if you have a project README or articulation of the scope of the project anywhere.

**Comment by cottojon** [comment]
It's a Senior-design/capstone project at ucf. It started off a NASA/Kennedy space center speech to text application. Using NASA JPL AUDREY for improving Kennedy Space Center voice transcriptions and a web app to listen, view, and update/train/correct voice clips/transcriptions. Unfortunately, NASA funding got shifted. Thus, in order to complete our senior design project, we are using DeepSpeech.

**Comment by daviddahl** [comment]
Thanks! I have been tinkering with DeepSpeech myself and would like to build a similar tool. Are there plans for audio capture or speaker identification?

**Comment by monik3r** [comment]
Audio capture will be handled externally, though silence detection, and splitting audio is planned on the roadmap (ie the ability to ingest longer clips into small clips of actual speech for easier representation/replaying).

Speaker ID isn't currently on the roadmap, although it'd be a neat thing to have. 

One thing that is interesting that we hope to support is retraining of the model to support environments with different background noise and different corpus in use in conversation (ie be able to transcribe audio better from mission-critical environments, and improve those transcriptions over time).

**Comment by monik3r** [comment]
Going to close this for now. If anyone has any further questions, feel free to re-open or make a new issue.
